# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
mappings_channel=official
mappings_version=1.18.2

minecraft_version=1.18.2
forge_version=40.2.17

# Curseforge File IDs
# 1.18.2-0.5.6 | https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4494903
rubidium_file_id=4494903
# 1.18.2 v4.12.94 | https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/5137931
architectury_file_id=5137931
# 1802.3.19-build.362 | https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/5423717
ftbchunks_file_id=5423717
# 1802.2.11-build.107 | https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge/files/4579981
ftbteams_file_id=4579981
# 1802.3.11-build.177 | https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/4396792
ftblib_file_id=4396792

# Curseforge Project IDs
rubidium_project_id=rubidium-574856
architectury_project_id=architectury-api-419699
ftbchunks_project_id=ftb-chunks-forge-314906
ftbteams_project_id=ftb-teams-forge-404468
ftblib_project_id=ftb-library-forge-404465
