# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
mappings_channel=official
mappings_version=1.18.2

minecraft_version=1.18.2
forge_version=40.2.17

# Curseforge File IDs
rubidium_file_id=4494903
architectury_file_id=5137931
ftbchunks_file_id=5423717
ftbteams_file_id=4579981
ftblib_file_id=4396792

# Curseforge Project IDs
rubidium_project_id=rubidium-574856
architectury_project_id=architectury-api-419699
ftbchunks_project_id=ftb-chunks-forge-314906
ftbteams_project_id=ftb-teams-forge-404468
ftblib_project_id=ftb-library-forge-404465
